name: auto check (legacy)

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'imgs/**'
  schedule:
    - cron: '0 5,17 * * *'
      timezone: 'Asia/Taipei'

jobs:
  build:
    name: glados/railgun legacy checkin
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      actions: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Running checkin
        env:
          GLADOS_COOKIES: ${{ secrets.GLADOS_COOKIES }}
          GLADOS_AUTO_EXCHANGE: 'false'
          GLADOS_EXCHANGE_CATALOG: '.github/glados/exchange_plans.json'
          PUSHDEER_SENDKEY: ${{ secrets.PUSHDEER_SENDKEY }}
          GLADOS_VERBOSE: ${{ secrets.GLADOS_VERBOSE }}
        run: python checkin.py
      - name: Keep alive
        uses: liskin/gh-workflow-keepalive@v1
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 7
          keep_minimum_runs: 7
          delete_run_by_conclusion_pattern: success
